DROP DATABASE IF EXISTS GeoJobSearch;

CREATE DATABASE GeoJobSearch CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE GeoJobSearch;

DROP TABLE IF EXISTS `Jobs`;
DROP TABLE IF EXISTS `Company`;
DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Company` (
    CompanyUID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    Province VARCHAR(255) NOT NULL,
    Address VARCHAR(255),
    Latitude DECIMAL(10, 8),
    Longitude DECIMAL(11, 8),
    PRIMARY KEY (CompanyUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Users` (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    HashedPassword VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Jobs` (
    JobID INT AUTO_INCREMENT,
    JobUID VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Company VARCHAR(255) NOT NULL,
    CompanyUID VARCHAR(255),
    Location VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    Province VARCHAR(255) NOT NULL,
    Description TEXT,
    Salary INT,
    JobType VARCHAR(255) NOT NULL,
    Date DATE,
    JobURL TEXT,
    PRIMARY KEY (JobUID),
    UNIQUE (JobID),
    FOREIGN KEY (CompanyUID) REFERENCES Company(CompanyUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('101computerinnovationsinc._calgary_ab', '101 Computer Innovations Inc.', 'Calgary', 'AB', '629 James Mckevitt Rd SW, Calgary, AB T2Y 2E7, Canada', 50.92123, -114.0742814);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('304260_markham_on', '304260', 'Markham', 'ON', 'Markham, ON, Canada', 43.8561002, -79.3370188);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('360insights_whitby_on', '360insights', 'Whitby', 'ON', '300 King St, Whitby, ON L1N 4Z4, Canada', 43.8762754, -78.9452603);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('3dpropertymanagement_saintjohn_nb', '3D Property Management', 'Saint John', 'NB', '215 Wentworth St, Saint John, NB E2L 2T4, Canada', 45.2690744, -66.0522018);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('a.r.thomsongroup_surrey_bc', 'A.R. THOMSON GROUP', 'Surrey', 'BC', '3420 189 St, Surrey, BC V3Z 1A7, Canada', 49.0640653, -122.6998161);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('abcrecyclingltd._burnaby_bc', 'ABC Recycling Ltd.', 'Burnaby', 'BC', '8081 Meadow Ave, Burnaby, BC V3N 2V9, Canada', 49.1940153, -122.9655705);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('abroadininc._toronto_on', 'Abroadin Inc.', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('accutive_remote_remote', 'Accutive', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('actlabs_ancaster_on', 'Actlabs', 'Ancaster', 'ON', 'Ancaster, Hamilton, ON, Canada', 43.2177791, -79.9872835);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('advancetravelinc_bedford_ns', 'Advance Travel Inc', 'Bedford', 'NS', '12 Ella Ln #211, Bedford, NS B4B 2M8, Canada', 44.7080466, -63.7105029);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('albertacollegeofmassagetherapy_edmonton_ab', 'Alberta College of Massage Therapy', 'Edmonton', 'AB', '9925 109 St NW Suite 101, Edmonton, AB T5K 2J8, Canada', 53.5378837, -113.5080905);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('albertagaming_liquorandcannabis_st.albert_ab', 'Alberta Gaming, Liquor and Cannabis', 'St. Albert', 'AB', '50 Corriveau Ave, St. Albert, AB T8N 3T5, Canada', 53.6413119, -113.5673703);

INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('albertaveterinarylaboratoriesltd_calgary_ab', 'Alberta Veterinary Laboratories Ltd', 'Calgary', 'AB', '7226 107 Ave SE, Calgary, AB T2C 5N6, Canada', 50.9592629, -113.9287102);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('amayaexpress_toronto_on', 'Amaya Express', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('amjcampbell_cambridge_on', 'AMJ Campbell', 'Cambridge', 'ON', '305 Industrial Rd #102, Cambridge, ON N3H 4R7, Canada', 43.4106622, -80.3344531);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ana-dataconsultinginc_remote_remote', 'Ana-Data Consulting Inc', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('anetcorpindiapvtltd_montréal_qc', 'Anetcorp India Pvt Ltd', 'Montréal', 'QC', 'Montreal, QC, Canada', 45.5018869, -73.5673919);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('anishinabekemploymentandtrainingservices_thunderbay_on', 'Anishinabek Employment and Training Services', 'Thunder Bay', 'ON', '285 Red River Rd, Thunder Bay, ON P7B 1A9, Canada', 48.4362598, -89.2235868);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('apextechfibercorp._vancouver_bc', 'Apextech Fiber Corp.', 'Vancouver', 'BC', '1111 W Hastings St Suite 600, Vancouver, BC V6E 2J3, Canada', 49.2883223, -123.1200015);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('appnerdincorporated_remote_remote', 'AppNerd Incorporated', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('aquapakindustriesltd._surrey_bc', 'Aquapak Industries Ltd.', 'Surrey', 'BC', '7398 132 St, Surrey, BC V3W 4M7, Canada', 49.1376014, -122.855639);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('arcuspowercorp_calgary_ab', 'Arcus Power Corp', 'Calgary', 'AB', '401 9 Ave SW #865, Calgary, AB T2P 3C5, Canada', 51.0444193, -114.069248);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('asamakaindustriesltd_windsor_on', 'ASAMAKA INDUSTRIES LTD', 'Windsor', 'ON', '1445 Argyle Rd, Windsor, ON N8Y 3K9, Canada', 42.3104343, -83.0032798);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('askireclamationlp_fortnelson_bc', 'Aski Reclamation LP', 'Fort Nelson', 'BC', 'Fort Nelson, BC V0C 1R0, Canada', 58.8050174, -122.697236);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('askireclamationlp_moberlylake_bc', 'Aski Reclamation LP', 'Moberly Lake', 'BC', 'R9GF+C6, Chetwynd, BC V0C 1X0, Canada', 55.8261505, -121.6269076);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('asp_markham_on', 'ASP', 'Markham', 'ON', 'Markham, ON, Canada', 43.8561002, -79.3370188);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('atcarscommerce_remote_remote', 'at Cars Commerce', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('atlanticedgecreditunion_happyvalley-goosebay_nl', 'Atlantic Edge Credit Union', 'Happy Valley-Goose Bay', 'NL', '328 Hamilton River Rd, Happy Valley-Goose Bay, NL A0P 1C0, Canada', 53.30219, -60.3696737);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('attaccountingandtaxservices_northyork_on', 'ATT Accounting and Tax Services', 'North York', 'ON', 'North York, ON, Canada', 43.7615377, -79.4110794);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('attrixtechnologies_mont-saint-hilaire_qc', 'AttriX Technologies', 'Mont-Saint-Hilaire', 'QC', '894 Bd Sir-Wilfrid-Laurier, Mont-Saint-Hilaire, QC J3H 6B7, Canada', 45.5740209, -73.1736896);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('aturapower_toronto_on', 'Atura Power', 'Toronto', 'ON', '470 Unwin Ave, Toronto, ON M4M 3B9, Canada', 43.6499794, -79.3309798);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('autumnwoodmaturelifestylecommunities_greatersudbury_on', 'Autumnwood Mature Lifestyle Communities', 'Greater Sudbury', 'ON', '30 Ste Anne Rd, Greater Sudbury, ON P3C 5E1, Canada', 46.4963603, -80.9958532);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('awd_woodbridge_on', 'AWD', 'Woodbridge', 'ON', 'Woodbridge, Vaughan, ON, Canada', 43.7761753, -79.609243);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('baycrest_toronto_on', 'Baycrest', 'Toronto', 'ON', '3560 Bathurst St, North York, ON M6A 2E1, Canada', 43.7295352, -79.4364784);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('bigbrothersofgreatervancouver_vancouver_bc', 'Big Brothers of Greater Vancouver', 'Vancouver', 'BC', '5118 Joyce St Unit #300, Vancouver, BC V5R 4H1, Canada', 49.237778, -123.032115);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('bitfirmsinc_burlington_on', 'BitFirms Inc', 'Burlington', 'ON', 'Burlington, ON, Canada', 43.3255196, -79.7990319);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('blueheronsupportservicesassociation_barrhead_ab', 'Blue Heron Support Services Association', 'Barrhead', 'AB', '5123 50 Ave., Barrhead, AB T7N 1A2, Canada', 54.1196168, -114.4078045);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('bluewatergroup_nanticoke_on', 'Bluewater Group', 'Nanticoke', 'ON', 'Nanticoke, ON N0A 1L0, Canada', 42.80907, -80.082283);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('bluvectechnologiesinc._burnaby_bc', 'Bluvec Technologies Inc.', 'Burnaby', 'BC', '3999 Henning Dr #102, Burnaby, BC V5C 6P9, Canada', 49.2655561, -123.0148628);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('breezybendcountryclub_headingley_mb', 'Breezy Bend Country Club', 'Headingley', 'MB', '7620 Roblin Blvd, Headingley, MB R4H 1A7, Canada', 49.8618507, -97.3728866);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cadstrom_montréal_qc', 'Cadstrom', 'Montréal', 'QC', 'Montreal, QC, Canada', 45.5018869, -73.5673919);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('canadalifeassurancecompany_toronto_on', 'Canada Life Assurance Company', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('canadaroyalmilk_kingston_on', 'Canada Royal Milk', 'Kingston', 'ON', '1680 Venture Dr, Kingston, ON K7P 0E9, Canada', 44.2737934, -76.5577352);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('canadianmentalhealthassociation_muskokaparry_bracebridge_on', 'Canadian Mental Health Association, Muskoka Parry', 'Bracebridge', 'ON', 'Bracebridge, ON, Canada', 45.0389565, -79.3078787);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('caprileotechpvtltd_remote_remote', 'Caprileo tech Pvt Ltd', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('caracaltechnologiesinc_vancouver_bc', 'Caracal Technologies Inc', 'Vancouver', 'BC', '1157 W 8th Ave, Vancouver, BC V6H 1C5, Canada', 49.2645838, -123.1303853);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('caroanalyticalservices_richmond_bc', 'CARO Analytical Services', 'Richmond', 'BC', '110 - 4011 Viking Way, #250, 4011 Viking Way Corporate Office, Richmond, BC V6V 2K9, Canada', 49.1838067, -123.0738645);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('carscommerce_toronto_on', 'Cars Commerce', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ccycinternationaleducationgroupinc._markham_on', 'CCYC International Education Group Inc.', 'Markham', 'ON', 'Markham, ON, Canada', 43.8561002, -79.3370188);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cégepheritagecollege_gatineau_qc', 'CÉGEP Heritage College', 'Gatineau', 'QC', '325 Bd de la Cité-des-Jeunes, Gatineau, QC J8Y 6T3, Canada', 45.4551959, -75.7648327);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('checkpointsystemsinc._toronto_on', 'Checkpoint Systems Inc.', 'Toronto', 'ON', '701 Evans Ave., Etobicoke, ON M9C 1A3, Canada', 43.6079026, -79.5571437);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofbrampton_brampton_on', 'City of Brampton', 'Brampton', 'ON', 'Brampton, ON, Canada', 43.7315479, -79.7624177);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofburnaby_burnaby_bc', 'City of Burnaby', 'Burnaby', 'BC', '6550 Bonsor Ave, Burnaby, BC V5H 3G4, Canada', 49.2242567, -122.9967536);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofedmonton_edmonton_ab', 'City of Edmonton', 'Edmonton', 'AB', '1 Sir Winston Churchill Square, Edmonton, AB T5J 2R7, Canada', 53.5460456, -113.4901955);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofmississauga_mississauga_on', 'City of Mississauga', 'Mississauga', 'ON', 'Mississauga, ON, Canada', 43.5852774, -79.6449916);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofregina_regina_sk', 'City of Regina', 'Regina', 'SK', '805 Toronto St, Regina, SK S4R 8G2, Canada', 50.465757, -104.598998);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofsaskatoon_saskatoon_sk', 'City of Saskatoon', 'Saskatoon', 'SK', 'Portage Ave, Saskatoon, SK S7J 4C8, Canada', 52.0920944, -106.6662316);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityofst.catharines_st.catharines_on', 'City of St. Catharines', 'St. Catharines', 'ON', 'St. Catharines, ON, Canada', 43.1621196, -79.2505817);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cityoftoronto_toronto_on', 'City of Toronto', 'Toronto', 'ON', 'Old Toronto, Toronto, ON, Canada', 43.6486795, -79.3803231);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('civicainfrastructureinc_woodbridge_on', 'Civica Infrastructure Inc', 'Woodbridge', 'ON', '155 Winges Rd, Woodbridge, ON L4L 6C7, Canada', 43.7868133, -79.5500644);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('classicgraniteandmarble_london_on', 'Classic Granite and Marble', 'London', 'ON', '565 Sovereign Rd, London, ON N5V 4K9, Canada', 43.0035034, -81.1475509);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('clearbrookchiropracticandmassageclinicinc._abbotsford_bc', 'Clearbrook Chiropractic and Massage Clinic Inc.', 'Abbotsford', 'BC', 'Clearbrook, Abbotsford, BC, Canada', 49.0515175, -122.3267647);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('clearsetvactruckservices_portcoquitlam_bc', 'Clearset vac truck services', 'Port Coquitlam', 'BC', '615 Laurier Ave, Port Coquitlam, BC V3C 3V4, Canada', 49.2749126, -122.728194);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cloudsquare_remote_remote', 'Cloudsquare', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('compestsolutionsinc_mississauga_on', 'Compest Solutions Inc', 'Mississauga', 'ON', 'Mississauga, ON, Canada', 43.5890452, -79.6441198);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('compestsolutionsinc_toronto_on', 'Compest Solutions Inc', 'Toronto', 'ON', '25 Waterman Ave, East York, ON M4B 1Y6, Canada', 43.7124451, -79.3157521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('copilotco._winnipeg_mb', 'CoPilot Co.', 'Winnipeg', 'MB', '62 Albert St #300, Winnipeg, MB R3B 1E9, Canada', 49.89659, -97.140463);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('countyofoxford_woodstock_on', 'County of Oxford', 'Woodstock', 'ON', '415 Hunter St, Woodstock, ON N4S 4G6, Canada', 43.131884, -80.7601081);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ctbakery_etobicoke_on', 'ct bakery', 'Etobicoke', 'ON', '25 Medulla Ave, Etobicoke, ON M8Z 5L6, Canada', 43.6229558, -79.5458648);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cyber-infomaxsolutionsinc._northyork_on', 'Cyber-Infomax Solutions Inc.', 'North York', 'ON', '25 Waterman Ave, East York, ON M4B 1Y6, Canada', 43.7124451, -79.3157521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cyber-infomaxsolutionsinc._toronto_on', 'Cyber-Infomax Solutions Inc.', 'Toronto', 'ON', '25 Waterman Ave, East York, ON M4B 1Y6, Canada', 43.7124451, -79.3157521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cyclenorthpowersports_princegeorge_bc', 'Cycle North Powersports', 'Prince George', 'BC', '5905 Gauthier Rd, Prince George, BC V2N 5M4, Canada', 53.849392, -122.826069);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cypresslandservices_calgary_ab', 'Cypress Land Services', 'Calgary', 'AB', '4838 Richard Rd SW #300, Calgary, AB T3E 6L1, Canada', 51.0104632, -114.126024);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('cypresssolutionsinc_burnaby_bc', 'Cypress Solutions Inc', 'Burnaby', 'BC', '3066 Beta Ave, Burnaby, BC V5G 4K4, Canada', 49.2565671, -122.9967082);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('damasci_mississauga_on', 'Damasci', 'Mississauga', 'ON', '4080 Confederation Pkwy #201, Mississauga, ON L5B 0G1, Canada', 43.5865475, -79.6473361);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dassmetalproducts_vaughan_on', 'Dass Metal Products', 'Vaughan', 'ON', '370 New Enterprise Way, Vaughan, ON L4H 0Z3, Canada', 43.7738816, -79.6398594);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('databasesolution_winnipeg_mb', 'Data base Solution', 'Winnipeg', 'MB', 'Winnipeg, MB, Canada', 49.8954221, -97.1385145);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dawninfotekinc._northyork_on', 'Dawn InfoTek Inc.', 'North York', 'ON', '302-200 Consumers Rd, North York, ON M2J 4R4, Canada', 43.7728361, -79.3311332);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dawninfotekinc._scarborough_on', 'Dawn InfoTek Inc.', 'Scarborough', 'ON', '302-200 Consumers Rd, North York, ON M2J 4R4, Canada', 43.7728361, -79.3311332);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dawninfotekinc._toronto_on', 'Dawn InfoTek Inc.', 'Toronto', 'ON', '302-200 Consumers Rd, North York, ON M2J 4R4, Canada', 43.7728361, -79.3311332);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('del-assistbookkeeping_bracebridge_on', 'Del-Assist Bookkeeping', 'Bracebridge', 'ON', '109-D Kimberley Ave, Bracebridge, ON P1L 1Z8, Canada', 45.041691, -79.3131584);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('delta9bio-techinc._winnipeg_mb', 'Delta 9 Bio-Tech Inc.', 'Winnipeg', 'MB', '827 Dakota St Unit 1, Winnipeg, MB R2M 5M2, Canada', 49.8304428, -97.1058727);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dfarc_charteredprofessionalaccountants_langley_bc', 'dfarc Chartered Professional Accountants', 'Langley', 'BC', 'Langley, BC, Canada', 49.1041779, -122.6603519);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('disposalkingltd._vancouver_bc', 'Disposal King Ltd.', 'Vancouver', 'BC', '8185 Main St, Vancouver, BC V5X 3L2, Canada', 49.2116149, -123.1025734);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dizolvegroupcorporation_moncton_nb', 'Dizolve Group Corporation', 'Moncton', 'NB', '270 Baig Blvd A1, Moncton, NB E1E 1C8, Canada', 46.0736654, -64.8278997);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dr.dianekjorven_inc_princegeorge_bc', 'Dr. Diane Kjorven, Inc.', 'Prince George', 'BC', '1531 8 Ave, Prince George, BC V2L 3R3, Canada', 53.914088, -122.7529481);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('dsbg_concord_on', 'DSBG', 'Concord', 'ON', '70 Great Gulf Dr #62, Vaughan, ON L4K 0K7, Canada', 43.7899589, -79.4951449);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('edienvironmentaldynamicsinc._grandeprairie_ab', 'EDI Environmental Dynamics Inc.', 'Grande Prairie', 'AB', '10071 120 Ave, Grande Prairie, AB T8V 8H8, Canada', 55.1874861, -118.799114);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('edienvironmentaldynamicsinc._princegeorge_bc', 'EDI Environmental Dynamics Inc.', 'Prince George', 'BC', '3810 18 Ave, Prince George, BC V2N 4V5, Canada', 53.9075443, -122.7900862);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ehealthsaskatchewan_regina_sk', 'eHealth Saskatchewan', 'Regina', 'SK', '2130 11th Ave, Regina, SK S4P 0J5, Canada', 50.4505663, -104.6120001);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('estruxturedatacenters_montréal_qc', 'Estruxture Data Centers', 'Montréal', 'QC', '800 Rue du Square-Victoria, Montréal, QC H4Z 1B7, Canada', 45.5003565, -73.5620759);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('exceedrobotics_mississauga_on', 'Exceed Robotics', 'Mississauga', 'ON', '3055 Argentia Rd B2, Mississauga, ON L5N 8E1, Canada', 43.5951914, -79.7867428);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ezofis_toronto_on', 'ezofis', 'Toronto', 'ON', '18 King St E Suite 1400, Toronto, ON M5H 1A1, Canada', 43.6490279, -79.3779912);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('familyandchildren''sservicesniagara_st.catharines_on', 'Family and Children''s Services Niagara', 'St. Catharines', 'ON', '82 Hannover Dr, St. Catharines, ON L2W 1A4, Canada', 43.1755988, -79.2770749);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('fgchealth_toronto_on', 'FGC Health', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('financialtransactionsandreportsanalysiscentre..._ottawa_on', 'Financial Transactions and Reports Analysis Centre...', 'Ottawa', 'ON', 'Centretown, Ottawa, ON, Canada', 45.415339, -75.696404);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('firstnationathletics_calgary_ab', 'First Nation Athletics', 'Calgary', 'AB', '800 5 Ave SW, Calgary, AB T2P 3T6, Canada', 51.0489931, -114.0788373);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('firstresponseontario_nanticoke_on', 'First Response Ontario', 'Nanticoke', 'ON', 'Nanticoke, ON N0A 1L0, Canada', 42.80907, -80.082283);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('flowmetrixtechnicalservices_concord_on', 'Flowmetrix Technical Services', 'Concord', 'ON', '15 Connie Crescent, Concord, ON L4K 1L3, Canada', 43.8206103, -79.4917197);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('foundingteams_remote_remote', 'Founding Teams', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('fraserhealth_newwestminster_bc', 'Fraser Health', 'New Westminster', 'BC', '505 6th St, New Westminster, BC V3L 3B9, Canada', 49.2121234, -122.9186878);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('fraserhealth_surrey_bc', 'Fraser Health', 'Surrey', 'BC', 'Surrey, BC, Canada', 49.1913466, -122.8490125);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('gatormininginc_winnipeg_mb', 'Gator Mining Inc', 'Winnipeg', 'MB', '319 Gunn Rd unit c, Winnipeg, MB R0E 1J3, Canada', 49.9160963, -97.0091873);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('gcbglovercustomsbrokersinc._ottawa_on', 'gcb Glover Customs Brokers Inc.', 'Ottawa', 'ON', '1510 Walkley Rd, Ottawa, ON K1V 6P5, Canada', 45.3752162, -75.6497913);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('gcomsupport_ottawa_on', 'GCOM Support', 'Ottawa', 'ON', '3735 St Joseph Blvd Unit E, Orléans, ON K1C 1T1, Canada', 45.4889825, -75.4821759);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('glenfiddichimmigration_calgary_ab', 'GLENFIDDICH IMMIGRATION', 'Calgary', 'AB', '5850 88 Ave NE #6240, Calgary, AB T3J 0Z7, Canada', 51.1334546, -113.9492587);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('governmentofalberta_edmonton_ab', 'Government of Alberta', 'Edmonton', 'AB', '10808 99 Ave, Edmonton, AB T5K 0G5, Canada', 53.5374951, -113.5071368);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('grayscalefineportraits_toronto_on', 'Grayscale Fine Portraits', 'Toronto', 'ON', '620 Wilson Ave Suite 100, North York, ON M3K 1Z3, Canada', 43.7323684, -79.4599151);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('greenfootenergysolutionsinc._moncton_nb', 'Greenfoot Energy Solutions Inc.', 'Moncton', 'NB', '43 Driscoll Crescent, Moncton, NB E1E 4C8, Canada', 46.0860681, -64.8371709);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('halliwellconsulting_scarborough_on', 'Halliwell Consulting', 'Scarborough', 'ON', 'Scarborough, ON, Canada', 43.7764258, -79.2317521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('harcodevelopmentsinc._calgary_ab', 'Harco Developments Inc.', 'Calgary', 'AB', '11450 Bearspaw Dam Rd NW, Calgary, AB T3B 5K2, Canada', 51.1037619, -114.2475956);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('harvestmanitoba_winnipeg_mb', 'Harvest Manitoba', 'Winnipeg', 'MB', '1085 Winnipeg Ave, Winnipeg, MB R3E 0S2, Canada', 49.9070338, -97.1738131);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('healthpei_charlottetown_pe', 'Health PEI', 'Charlottetown', 'PE', '16 Garfield St, Charlottetown, PE C1A 6A5, Canada', 46.2529554, -63.1116603);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('helmpropertymanagement&realtyltd._edmonton_ab', 'Helm Property Management & Realty Ltd.', 'Edmonton', 'AB', '15533 Stony Plain Rd, Edmonton, AB T5P 3Z1, Canada', 53.5410909, -113.589346);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('hollingsgateworkforcesolutions_remote_remote', 'Hollingsgate Workforce solutions', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('hroptions_inc_toronto_on', 'HR Options, Inc.', 'Toronto', 'ON', '3601 Hwy 7 #1005, Markham, ON L3R 0M3, Canada', 43.8538428, -79.3382835);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ikoindustriesltd._brampton_on', 'IKO Industries Ltd.', 'Brampton', 'ON', '40 Hansen Rd S, Brampton, ON L6W 3H4, Canada', 43.6945792, -79.7393427);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ilinksystemsinc._remote_remote', 'iLink Systems Inc.', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('initialsecurityservice_abbotsford_bc', 'Initial Security Service', 'Abbotsford', 'BC', 'Abbotsford, BC, Canada', 49.0504377, -122.3044697);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('innospheresdgltd_remote_remote', 'Innosphere SDG Ltd', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('internetserviceprovider_remote_remote', 'Internet Service Provider', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('itnfoodcorporation_woodbridge_on', 'ITN Food Corporation', 'Woodbridge', 'ON', 'Woodbridge, Vaughan, ON, Canada', 43.7761753, -79.609243);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('itspecialists_calgary_ab', 'IT Specialists', 'Calgary', 'AB', '111 5 Ave SW #100, Calgary, AB T2P 3Y6, Canada', 51.0479372, -114.0638655);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('jaffergroupofcompanies_edmonton_ab', 'Jaffer Group of Companies', 'Edmonton', 'AB', '10133 97 St NW Suite 200, Edmonton, AB T5J 0L2, Canada', 53.5428693, -113.4853165);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('janemidentalgroup_london_on', 'Janemi Dental Group', 'London', 'ON', 'London, ON, Canada', 42.9849233, -81.2452768);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('jbsequipment_mission_bc', 'JBS Equipment', 'Mission', 'BC', '7268 Fraserview Pl, Mission, BC V4S 0A3, Canada', 49.1342228, -122.3529849);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('keeptechnologies_ottawa_on', 'Keep Technologies', 'Ottawa', 'ON', 'Ottawa, ON, Canada', 45.4215296, -75.6971931);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('kgogroupltd._mississauga_on', 'KGO Group Ltd.', 'Mississauga', 'ON', '2172 Wyecroft Rd, Oakville, ON L6L 6R1, Canada', 43.4168309, -79.7265544);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('kidsability_waterloo_on', 'KidsAbility', 'Waterloo', 'ON', 'Head Office, 500 Hallmark Dr, Waterloo, ON N2K 3P5, Canada', 43.4982957, -80.5182758);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('klaassengroupofcompanies_chilliwack_bc', 'Klaassen Group of Companies', 'Chilliwack', 'BC', '51211 Chilliwack Central Rd, Chilliwack, BC V0X 1X0, Canada', 49.161418, -121.807366);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('kncomputersandnetworking_markham_on', 'KN Computers and Networking', 'Markham', 'ON', '55 Albert St Suite 100, Markham, ON L3P 3T4, Canada', 43.8780166, -79.2575524);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('krbavocats_montréal_qc', 'KRB Avocats', 'Montréal', 'QC', '300-240, Rue Saint-Jacques, Montréal, QC H2Y 1L9, Canada', 45.503442, -73.558492);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ksiconsulting_remote_remote', 'KSI Consulting', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('kwikwetlemfirstnation_portcoquitlam_bc', 'Kwikwetlem First Nation', 'Port Coquitlam', 'BC', '2-65 Colony Farm Rd, Coquitlam, BC V3C 5X9, Canada', 49.2300589, -122.8061118);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('laurentianuniversity_greatersudbury_on', 'Laurentian University', 'Greater Sudbury', 'ON', '935 Ramsey Lake Rd, Sudbury, ON P3E 2C6, Canada', 46.4672485, -80.9757296);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('leedsgrenville_brockville_on', 'Leeds Grenville', 'Brockville', 'ON', 'Brockville, ON, Canada', 44.5895244, -75.6842858);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('legendfleetsolutions_tillsonburg_on', 'Legend Fleet Solutions', 'Tillsonburg', 'ON', '56957 ON-3, Tillsonburg, ON N4G 4G8, Canada', 42.8276033, -80.7732828);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('lewisfinancialservicesinc._sylvanlake_ab', 'Lewis Financial Services Inc.', 'Sylvan Lake', 'AB', '40 Hewlett Park Landing #6, Sylvan Lake, AB T4S 2J3, Canada', 52.3049997, -114.0769521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('livepatrol_victoria_bc', 'Live Patrol', 'Victoria', 'BC', '19 Bastion Square #301, Victoria, BC V8W 1J1, Canada', 48.425633, -123.369385);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('logicaldoxinc._markham_on', 'LogicalDox Inc.', 'Markham', 'ON', '7030 Woodbine Ave Suite 600, Markham, ON L3R 6G2, Canada', 43.8142822, -79.35034);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('longtermtechnologyservicesinc._london_on', 'Longterm Technology Services Inc.', 'London', 'ON', '255 Queens Ave #1860, London, ON N6A 5R8, Canada', 42.9857046, -81.2466345);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('loyalisttownship_amherstview_on', 'Loyalist Township', 'Amherstview', 'ON', 'Amherstview, Loyalist, ON K7N 1C3, Canada', 44.223329, -76.650818);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mainlandmotorslangley_langley_bc', 'Mainland Motors Langley', 'Langley', 'BC', '5933 200 St, Langley, BC V3A 1N2, Canada', 49.1101105, -122.6690287);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('manitobagovernment_winnipeg_mb', 'Manitoba Government', 'Winnipeg', 'MB', '227 Provencher Blvd, Winnipeg, MB R2H 0G4, Canada', 49.8934123, -97.1203858);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('maverickindustriesltd_morden_mb', 'Maverick Industries Ltd', 'Morden', 'MB', '30005 Hwy 3, Morden, MB R6M 1B3, Canada', 49.193483, -98.140484);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mcrecrutementetconsultation_montréal-est_qc', 'MC RECRUTEMENT ET CONSULTATION', 'Montréal-Est', 'QC', 'Montréal-Est, QC, Canada', 45.6320003, -73.5066981);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('media6img_mississauga_on', 'Media6 IMG', 'Mississauga', 'ON', '895 Lakefront Promenade, Mississauga, ON L5E 2C2, Canada', 43.5736536, -79.5577976);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mercedesbenzpeterborough_peterborough_on', 'Mercedes Benz Peterborough', 'Peterborough', 'ON', '995 Crawford Dr, Peterborough, ON K9J 3X1, Canada', 44.2698211, -78.3383712);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mi''kmawnativefriendshipcentre_windsor_ns', 'Mi''kmaw Native Friendship Centre', 'Windsor', 'NS', 'Windsor, NS, Canada', 44.9902861, -64.1310364);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('michelangelo_lachine_qc', 'Michelangelo', 'Lachine', 'QC', '1400 46e Avenue, Lachine, QC H8T 3R3, Canada', 45.453189, -73.7094948);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('microhardsystemsinc._calgary_ab', 'Microhard Systems Inc.', 'Calgary', 'AB', '150 Country Hills Landing NW, Calgary, AB T3K 5P3, Canada', 51.1429053, -114.0754494);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ministryoftheattorneygeneral_cornwall_on', 'Ministry of the Attorney General', 'Cornwall', 'ON', 'Ontario, Canada', 51.253775, -85.3232139);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ministryoftheenvironment_conservationand_alliston_on', 'Ministry of the Environment, Conservation and...', 'Alliston', 'ON', 'Alliston, New Tecumseth, ON, Canada', 44.1539514, -79.8691544);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('minitipi_gatineau_qc', 'Mini Tipi', 'Gatineau', 'QC', '670 Rue Auguste Mondoux #2, Gatineau, QC J9J 3K3, Canada', 45.4431247, -75.813181);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mira_remote_remote', 'Mira', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mohawkcollege_hamilton_on', 'Mohawk College', 'Hamilton', 'ON', 'Hamilton, ON, Canada', 43.2557206, -79.8711024);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mollymaidcanada_oakville_on', 'Molly Maid Canada', 'Oakville', 'ON', '3485 Rebecca St Suite 101, Oakville, ON L6L 0H4, Canada', 43.3829773, -79.7367187);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('mycmedia_mississauga_on', 'MYC Media', 'Mississauga', 'ON', '1146 Westport Crescent Unit 2, Mississauga, ON L5T 1G1, Canada', 43.6525521, -79.6596032);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('naijavilla/suyacity_northyork_on', 'Naija Villa/Suya City', 'North York', 'ON', '750 Oakdale Rd Unit 1, North York, ON M3N 2Z4, Canada', 43.751326, -79.5286009);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('niagararegion_niagara_on', 'Niagara Region', 'Niagara', 'ON', 'Regional Municipality of Niagara, ON, Canada', 43.0581645, -79.2902133);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('northbaycity_northbay_on', 'North Bay City', 'North Bay', 'ON', 'North Bay, ON, Canada', 46.3293087, -79.4661009);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('northterraconstructionltd._concord_on', 'North Terra Construction Ltd.', 'Concord', 'ON', '421 Bowes Rd, Concord, ON L4K 1J5, Canada', 43.8136061, -79.4943225);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('nunastarpropertiesinc._edmonton_ab', 'Nunastar Properties Inc.', 'Edmonton', 'AB', '200, 1281 91 St SW, Edmonton, AB T6X 1H1, Canada', 53.4211353, -113.4760323);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('oaksoutpatientaddictionclinic_elliotlake_on', 'Oaks Outpatient Addiction Clinic', 'Elliot Lake', 'ON', 'Elliot Lake, ON, Canada', 46.386179, -82.650941);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('oakvalleyhealth_markham_on', 'Oak Valley Health', 'Markham', 'ON', '381 Church St, Markham, ON L3P 7P3, Canada', 43.883679, -79.2316744);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ogaco_vancouver_bc', 'OGACO', 'Vancouver', 'BC', 'Vancouver, BC, Canada', 49.2827291, -123.1207375);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('okanagancollege_kelowna_bc', 'Okanagan College', 'Kelowna', 'BC', 'Kelowna, BC, Canada', 49.8863235, -119.4965917);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('olympicinternationalsales_northvancouver_bc', 'Olympic International Sales', 'North Vancouver', 'BC', '930 W 1st St Suite # 112, North Vancouver, BC V7P 3N4, Canada', 49.3186367, -123.0998403);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('onevascularimaging_hamilton_on', 'One Vascular Imaging', 'Hamilton', 'ON', '35 Upper Centennial Pkwy #3C, Stoney Creek, ON L8J 2T6, Canada', 43.1784433, -79.7748196);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ottawapoliceassociation_ottawa_on', 'Ottawa Police Association', 'Ottawa', 'ON', '141 Catherine St, Ottawa, ON K2P 1C3, Canada', 45.4103736, -75.6907119);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('paaytoo_mississauga_on', 'Paaytoo', 'Mississauga', 'ON', 'Mississauga, ON, Canada', 43.5890452, -79.6441198);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('parkvacationmanagement_fernie_bc', 'Park Vacation Management', 'Fernie', 'BC', 'Fernie, BC, Canada', 49.5040452, -115.063065);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('peakproconstructionmanagementltd_metrovancouverregionaldistrict_bc', 'Peak Pro Construction Management Ltd', 'Metro Vancouver Regional District', 'BC', '100 Park Royal S, West Vancouver, BC V7T 1A2, Canada', 49.3252564, -123.1335654);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('peelhr_concord_on', 'Peel Hr', 'Concord', 'ON', 'Concord, Vaughan, ON L4K, Canada', 43.798329, -79.5079073);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('phsa_burnaby_bc', 'PHSA', 'Burnaby', 'BC', '1795 Willingdon Ave, Burnaby, BC V5C 6E3, Canada', 49.2684805, -123.0036256);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('phsa_kelowna_bc', 'PHSA', 'Kelowna', 'BC', 'Kelowna, BC, Canada', 49.8863235, -119.4965917);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('phsa_vancouver_bc', 'PHSA', 'Vancouver', 'BC', '1380 Burrard St, Vancouver, BC V6Z 2K2, Canada', 49.2768106, -123.1315216);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('phsa_victoria_bc', 'PHSA', 'Victoria', 'BC', 'Victoria, BC, Canada', 48.4284207, -123.3656444);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('pillexa_surrey_bc', 'Pillexa', 'Surrey', 'BC', 'Surrey, BC, Canada', 49.1913466, -122.8490125);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('pinnaclecustomcabinets_chilliwack_bc', 'Pinnacle Custom Cabinets', 'Chilliwack', 'BC', '45920 Rowat Ave Unit E, Chilliwack, BC V2P 1J3, Canada', 49.1617339, -121.9537479);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('pixlworksproductions_remote_remote', 'Pixlworks Productions', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('pleacommunityservicessocietyofbc_vancouver_bc', 'PLEA Community Services Society of BC', 'Vancouver', 'BC', '3894 Commercial St, Vancouver, BC V5N 4G2, Canada', 49.250442, -123.0678178);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('plumbineersplumbing&heatinginc._whitehorse_yt', 'Plumbineers Plumbing & Heating Inc.', 'Whitehorse', 'YT', '118B Galena Rd, Whitehorse, YT Y1A 2W6, Canada', 60.742549, -135.0736281);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('portfolioaidinc._toronto_on', 'PortfolioAid Inc.', 'Toronto', 'ON', '2 St Clair Ave W suite 605, Toronto, ON M4V 1L5, Canada', 43.6883105, -79.3946408);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('posturepro_mont-royal_qc', 'POSTUREPRO', 'Mont-royal', 'QC', '4810 Rue Jean-Talon O #214b, Montreal, QC H4P 2N5, Canada', 45.4980718, -73.6473517);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('powerproselectricalltd._abbotsford_bc', 'Power Pros Electrical Ltd.', 'Abbotsford', 'BC', '30445 Progressive Way #2, Abbotsford, BC V2T 6W3, Canada', 49.0489466, -122.3797874);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('prioautosales_nepean_on', 'Prio Auto Sales', 'Nepean', 'ON', '63 Roydon Pl, Ottawa, ON K2E 1A3, Canada', 45.3392113, -75.7220784);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('prostockathleticsupply_burnaby_bc', 'Prostock Athletic Supply', 'Burnaby', 'BC', '8327 Eastlake Dr #109, Burnaby, BC V5A 4W2, Canada', 49.258154, -122.9223698);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('publichealthontario_toronto_on', 'Public Health Ontario', 'Toronto', 'ON', '480 University Ave #300, Toronto, ON M5G 1V2, Canada', 43.6550684, -79.3888853);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('publicservicesandprocurementcanada_shediac_nb', 'Public Services and Procurement Canada', 'Shediac', 'NB', 'Shediac, NB, Canada', 46.2201972, -64.5346866);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('quotainc_remote_remote', 'Quota Inc', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('rcpetproducts_vancouver_bc', 'RC Pet Products', 'Vancouver', 'BC', '310 East Kent Ave S, Vancouver, BC V5X 4N6, Canada', 49.207042, -123.0998539);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('re/maxrealestatecentreinc._mississauga_on', 'RE/MAX REAL ESTATE CENTRE INC.', 'Mississauga', 'ON', '1140 Burnhamthorpe Rd W Ste 141, Mississauga, ON L5C 4E9, Canada', 43.5689375, -79.6621956);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('regentparkcommunityhealthcentre_toronto_on', 'Regent Park Community Health Centre', 'Toronto', 'ON', '465 Dundas St E 2nd Floor, Toronto, ON M5A 2B2, Canada', 43.6594084, -79.3654585);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('regionexextermination_gatineau_qc', 'Regionex Extermination', 'Gatineau', 'QC', '18 De Villebois, Gatineau, QC J8T 8J7, Canada', 45.4913591, -75.7048413);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('reliancefoundry_langley_bc', 'Reliance Foundry', 'Langley', 'BC', 'Langley, BC, Canada', 49.1041779, -122.6603519);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('revinate_vancouver_bc', 'Revinate', 'Vancouver', 'BC', 'Vancouver, BC, Canada', 49.2827291, -123.1207375);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('rosewoodhotelgeorgia_vancouver_bc', 'Rosewood Hotel Georgia', 'Vancouver', 'BC', '801 W Georgia St, Vancouver, BC V6C 1P7, Canada', 49.283465, -123.119031);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('royalautobody2020ltd._edmonton_ab', 'Royal Auto Body 2020 Ltd.', 'Edmonton', 'AB', '16831 107 Ave NW, Edmonton, AB T5P 0Y8, Canada', 53.5524096, -113.6114455);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('ruralmunicipalityofcartier_elie_mb', 'Rural Municipality of Cartier', 'Elie', 'MB', '28 MB-248, Elie, MB R0H 0H0, Canada', 49.9022822, -97.7576998);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('scentroid(divisionofidescanadainc.)_stouffville_on', 'Scentroid (division of Ides Canada Inc.)', 'Stouffville', 'ON', '70 Innovator Ave Unit 7, Whitchurch-Stouffville, ON L4A 0Y2, Canada', 43.9620935, -79.2676235);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('shrinerschildren''s_montréal_qc', 'Shriners Children''s', 'Montréal', 'QC', '1003 Bd Décarie, Montréal, QC H4A 0A9, Canada', 45.4717608, -73.6015906);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('shuswapchildren''sassociation_salmonarm_bc', 'Shuswap Children''s Association', 'Salmon Arm', 'BC', '240 Shuswap St S, Salmon Arm, BC V1E 4R5, Canada', 50.701463, -119.284995);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('signetjewelers-field_markham_on', 'Signet Jewelers - Field', 'Markham', 'ON', 'Markham, ON, Canada', 43.8561002, -79.3370188);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('smartsetterinc_remote_remote', 'SmartSetter Inc', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('snappyinnovationinc._markham_on', 'Snappy Innovation Inc.', 'Markham', 'ON', '7100 Woodbine Ave Suite 300, Markham, ON L3R 5J2, Canada', 43.8159156, -79.3496991);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('springberrimanpsychotherapy&counselling_remote_remote', 'Spring Berriman Psychotherapy & Counselling', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('st.joseph''shealthcarehamilton_hamilton_on', 'St. Joseph''s Healthcare Hamilton', 'Hamilton', 'ON', 'Hamilton, ON, Canada', 43.2557206, -79.8711024);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('starportmanagedservices_summerside_pe', 'Starport Managed Services', 'Summerside', 'PE', 'Summerside, PE, Canada', 46.3933777, -63.7902331);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('starsorthodontics_ottawa_on', 'Stars Orthodontics', 'Ottawa', 'ON', '239B Argyle Ave, Ottawa, ON K2P 1B8, Canada', 45.4113088, -75.6917358);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('succulentchocolatesandsweetsinc._woodbridge_on', 'Succulent Chocolates and Sweets Inc.', 'Woodbridge', 'ON', '501 Rowntree Dairy Rd #3, Woodbridge, ON L4L 8H1, Canada', 43.780567, -79.560256);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('summervillagesonsylvanlake_sylvanlake_ab', 'Summer Villages on Sylvan Lake', 'Sylvan Lake', 'AB', '2 Erickson Dr, Sylvan Lake, AB T4S 1P5, Canada', 52.3162471, -114.0727533);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('sunglowwindowcoveringproductsofcanadaltd._eastyork_on', 'Sun Glow Window Covering Products of Canada Ltd.', 'East York', 'ON', '50 Hollinger Rd, East York, ON M4B 3G5, Canada', 43.7147284, -79.3132635);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('symbioticai_calgary_ab', 'Symbiotic AI', 'Calgary', 'AB', '3655 36 St NW, Calgary, AB T2L 1Y8, Canada', 51.0846148, -114.1399521);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('symphonysolutionsinc_vancouver_bc', 'Symphony Solutions Inc', 'Vancouver', 'BC', '800 W Pender St #1220, Vancouver, BC V6C 2V6, Canada', 49.2853547, -123.1164818);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('synechroncanadainc._montréal_qc', 'Synechron Canada Inc.', 'Montréal', 'QC', '1250 Boul. René-Lévesque O suite 3000, Montréal, QC H3B 4W8, Canada', 45.4978525, -73.5708804);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('talenttech_montréal_qc', 'TalentTECH', 'Montréal', 'QC', '510 St Laurent Blvd #200, Montreal, QC H2Y 2Y9, Canada', 45.5062612, -73.5560683);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tamarackindustries_winnipeg_mb', 'Tamarack Industries', 'Winnipeg', 'MB', '1205 Sherwin Rd, Winnipeg, MB R3H 0V1, Canada', 49.9140823, -97.210824);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tantalus_burnaby_bc', 'Tantalus', 'Burnaby', 'BC', '3555 Gilmore Wy #200, Burnaby, BC V5G 0B3, Canada', 49.2529825, -123.0114263);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('techtronicinnovationsltd._mississauga_on', 'Techtronic Innovations Ltd.', 'Mississauga', 'ON', '7461 Pacific Cir, Mississauga, ON L5T 2A4, Canada', 43.6558917, -79.6737136);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tekgroup_markham_on', 'TEK Group', 'Markham', 'ON', 'Markham, ON, Canada', 43.8561002, -79.3370188);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tekshapers_toronto_on', 'tekshapers', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thebridggroupofcompanies_woodbridge_on', 'The BridgGroup of Companies', 'Woodbridge', 'ON', 'Woodbridge, Vaughan, ON, Canada', 43.7761753, -79.609243);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thecentrefordermatolgy_richmondhill_on', 'The Centre for Dermatolgy', 'Richmond Hill', 'ON', '312 Hwy 7, Richmond Hill, ON L4B 1A5, Canada', 43.8405293, -79.4013303);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thecityofvancouver_vancouver_bc', 'The City of Vancouver', 'Vancouver', 'BC', 'Dusty Greenwell Park, 2799 Wall St, Vancouver, BC V5K, Canada', 49.2922463, -123.0476618);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thedistrictofthunderbaysocialservices..._thunderbay_on', 'The District of Thunder Bay Social Services...', 'Thunder Bay', 'ON', 'Thunder Bay, ON, Canada', 48.3808951, -89.2476823);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('theroyalconservatory_toronto_on', 'The Royal Conservatory', 'Toronto', 'ON', '273 Bloor St W, Toronto, ON M5S 1W2, Canada', 43.6679716, -79.3963244);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thewhartonmedicalclinicclinicaltrialsinc_hamilton_on', 'The Wharton Medical Clinic Clinical Trials Inc', 'Hamilton', 'ON', 'Hamilton, ON, Canada', 43.2557206, -79.8711024);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('thormotors_orillia_on', 'Thor Motors', 'Orillia', 'ON', '201 Gill St, Orillia, ON L3V 6K7, Canada', 44.604483, -79.410224);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tidusgroupltd_kingston_on', 'Tidus Group LTD', 'Kingston', 'ON', '631 Fortune Crescent #7, Kingston, ON K7P 0L5, Canada', 44.2730202, -76.5673586);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tidusgroupltd_northyork_on', 'Tidus Group LTD', 'North York', 'ON', 'North York, ON, Canada', 43.7615377, -79.4110794);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tidusgroupltd_toronto_on', 'Tidus Group LTD', 'Toronto', 'ON', '79 Woodycrest Ave, Toronto, ON M4J 3A8, Canada', 43.6825424, -79.3426068);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tilray_remote_remote', 'Tilray', 'Remote', 'Remote', NULL, NULL, NULL);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tootsiimpexinc_saint-laurent_qc', 'TOOTSI IMPEX INC', 'Saint-Laurent', 'QC', '8800 Bd Henri Bourassa O, Saint-Laurent, QC H4S 1P4, Canada', 45.5011915, -73.7456314);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('torontoandregionconservationauthority(trca)_woodbridge_on', 'Toronto and Region Conservation Authority (TRCA)', 'Woodbridge', 'ON', 'Woodbridge, Vaughan, ON, Canada', 43.7761753, -79.609243);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('totallife_edmonton_ab', 'Total Life', 'Edmonton', 'AB', 'Edmonton, AB, Canada', 53.5460983, -113.4937266);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('townautobodyandcarsales_winnipeg_mb', 'TOWN AUTOBODY AND CAR SALES', 'Winnipeg', 'MB', '64 Salter St, Winnipeg, MB R2W 4J6, Canada', 49.9122597, -97.1436049);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('truckrightdatamanagementinc._belleville_on', 'TruckRight Data Management Inc.', 'Belleville', 'ON', '80 Harriett St, Belleville, ON K8P 1V7, Canada', 44.1694977, -77.3929691);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('tungthihelectroniccanadaresearch&development..._richmondhill_on', 'Tung Thih Electronic Canada Research&Development...', 'Richmond Hill', 'ON', 'Richmond Hill, ON, Canada', 43.8828401, -79.4402808);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('unboxyourpartycanada_toronto_on', 'Unbox Your Party Canada', 'Toronto', 'ON', '651 Mt Pleasant Rd, Toronto, ON M4S 2N2, Canada', 43.7054177, -79.3887013);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('unitedroofinginc._calgary_ab', 'United Roofing Inc.', 'Calgary', 'AB', '3195 9 St SE, Calgary, AB T2G 3C1, Canada', 51.0260628, -114.0409635);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('universityhealthnetwork_toronto_on', 'University Health Network', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('universityofalberta_edmonton_ab', 'University of Alberta', 'Edmonton', 'AB', 'University Of Alberta, Edmonton, AB T6G, Canada', 53.5229047, -113.5255794);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('universityofottawa_ottawa_on', 'University of Ottawa', 'Ottawa', 'ON', '75 Laurier Ave E, Ottawa, ON K1N 6N5, Canada', 45.4231064, -75.6831329);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('universityoftoronto_toronto_on', 'University of Toronto', 'Toronto', 'ON', '27 King''s College Cir, Toronto, ON M5S 1A1, Canada', 43.6634932, -79.3960598);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('vaniercollege_vanier_qc', 'Vanier College', 'Vanier', 'QC', '821 Av. Sainte-Croix, Saint-Laurent, QC H4L 3X9, Canada', 45.5144626, -73.6755719);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('vasquezlawoffice_nepean_on', 'Vasquez Law Office', 'Nepean', 'ON', '38 Auriga Dr Suite#200, Nepean, ON K2E 8A5, Canada', 45.3314483, -75.7056804);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('velocitymechanicalinc_kitchener_on', 'Velocity Mechanical Inc', 'Kitchener', 'ON', '176 Forfar Ave, Kitchener, ON N2B 3A1, Canada', 43.4665317, -80.4540122);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('venuiti_kitchener_on', 'Venuiti', 'Kitchener', 'ON', '283 Duke St W, Kitchener, ON N2H 3X7, Canada', 43.4548301, -80.4972143);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('vidrives_nanaimo_bc', 'VI Drives', 'Nanaimo', 'BC', '2595 Bowen Rd, Nanaimo, BC V9T 3L4, Canada', 49.2038693, -124.0019337);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('visionquestadvisors_kamloops_bc', 'VisionQuest Advisors', 'Kamloops', 'BC', 'Kamloops, BC, Canada', 50.674522, -120.3272674);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('vitalhub_toronto_on', 'VitalHub', 'Toronto', 'ON', '44 Victoria St, Toronto, ON M5C 1Y2, Canada', 43.6503921, -79.3772798);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('voronoihealthanalyticsincorporated_metrovancouverregionaldistrict_bc', 'Voronoi Health Analytics Incorporated', 'Metro Vancouver Regional District', 'BC', '997 Seymour St #250, Vancouver, BC V6B 3M1, Canada', 49.2789504, -123.1219297);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('waapihkresearch_winnipeg_mb', 'Waapihk Research', 'Winnipeg', 'MB', '191 Lombard Ave #1000, Winnipeg, MB R3B 0X1, Canada', 49.8964912, -97.1383934);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wagenersmeatproducts_toronto_on', 'Wageners Meat Products', 'Toronto', 'ON', '44 Six Point Rd #40, Toronto, ON M8Z 2X2, Canada', 43.6360676, -79.5272677);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wainwrightchildren''scentre_wainwright_ab', 'Wainwright Children''s Centre', 'Wainwright', 'AB', '905 10 St, Wainwright, AB T9W 2R6, Canada', 52.839077, -110.853727);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('weedme_pickering_on', 'Weed Me', 'Pickering', 'ON', 'Pickering, ON, Canada', 43.8384117, -79.0867579);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('weirconceptsinc._edmonton_ab', 'Weir Concepts Inc.', 'Edmonton', 'AB', '7596 Wagner Rd NW, Edmonton, AB T6E 5B2, Canada', 53.5016383, -113.4447157);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('williamsmachinery_terrace_bc', 'Williams Machinery', 'Terrace', 'BC', '5506 Highway 16 West, Terrace, BC V8G 0C6, Canada', 54.5183452, -128.644437);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wilsonsheating_truro_ns', 'Wilsons Heating', 'Truro', 'NS', 'Truro, NS, Canada', 45.3646224, -63.2765061);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('woodbuffaloenvironmentalassociation(wbea)_fortmcmurray_ab', 'Wood Buffalo Environmental Association (WBEA)', 'Fort McMurray', 'AB', '805 Memorial Dr #3, Fort McMurray, AB T9K 0K4, Canada', 56.7651901, -111.4234924);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('woodlandmills_portperry_on', 'Woodland Mills', 'Port Perry', 'ON', '1431 Scugog Line 6, Port Perry, ON L9L 0C3, Canada', 44.0949974, -78.9711151);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wreno_calgary_ab', 'Wreno', 'Calgary', 'AB', 'Reno, AB T0H 2R0, Canada', 55.984448, -117.001202);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wrightplaninc._waterloo_on', 'WrightPlan Inc.', 'Waterloo', 'ON', '285 Weber St N B3, Waterloo, ON N2J 3H8, Canada', 43.4797234, -80.5233905);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('wsnconstruction_cambridge_on', 'WSN Construction', 'Cambridge', 'ON', '48 Cowansview Rd, Cambridge, ON N1R 7N3, Canada', 43.3950297, -80.3067371);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('y&mmaintenance&cleaningservices.since"1997"_ottawa_on', 'Y&M Maintenance & Cleaning Services. Since "1997"', 'Ottawa', 'ON', '5509 Canotek Rd Unit 16, Ottawa, ON K1J 9J8, Canada', 45.4570927, -75.5833549);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('yorkuniversity_toronto_on', 'York University', 'Toronto', 'ON', 'Toronto, ON, Canada', 43.653226, -79.3831843);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('zagimemanagementauthorityltd_regina_sk', 'Zagime Management Authority Ltd', 'Regina', 'SK', '2825 Saskatchewan Dr, Regina, SK S4T 1H3, Canada', 50.4500817, -104.6217727);
INSERT INTO Company (CompanyUID, Name, City, Province, Address, Latitude, Longitude) VALUES ('zebrarobotics_shelburne_on', 'Zebra Robotics', 'Shelburne', 'ON', 'Shelburne, ON L9V, Canada', 44.079119, -80.2011728);
